Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 6
    libvirt.memory = 6144
    libvirt.driver = "kvm"
  end

  # Nodo maestro
  config.vm.define "master" do |master|
    master.vm.hostname = "k8s-master"
    master.vm.network :private_network, ip: "192.168.50.10"
  end

  # Nodos trabajadores
  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "k8s-node#{i}"
      node.vm.network :private_network, ip: "192.168.50.#{10 + i}"
      # Ejecutar Ansible solo en el último nodo para asegurar que todos estén arriba
      if i == 7
        node.vm.provision "ansible" do |ansible|
          ansible.playbook = "../ansible/playbooks/setup_cluster.yml"
          ansible.limit = "all"
          ansible.groups = {
            "master" => ["master"],
            "workers" => ["node[1:2]"]
          }
          
          ansible.extra_vars = {
            "pod_network_cidr" => "10.244.0.0/16",
            "apiserver_advertise_address" => "192.168.50.10"
          }
        end
      end
    end
  end
end